# Generated by Django 2.0.7 on 2019-04-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
